### ISSUE TITLE
Set up a Github workflow for publishing release to Maven Central

### ISSUE THREAD

**Issue by carlspring** [carlspring/idempotence#11]
# Task Description

We need to set up a Github Workflow for publishing releases to Maven Central.

# Open Questions

# Notes

# Task List

The following tasks will need to be carried out:
* [x] Investigate the issue.
* [x] Provide a solution.
* [x] Test the fix.
* [x] Update the documentation.

# Useful Commands

# Incurred Costs

# Task Relationships

This task:
* Is a sub-task of: 
* Depends on: 
* Is a follow-up of: 
* Relates to: 

# Resources

# Useful Links

# Points of Contact

* @carlspring

**Comment by carlspring** [comment]
Implemented.
