### ISSUE TITLE
Set up documentation using mkdocs

### ISSUE THREAD

**Issue by carlspring** [carlspring/idempotence#22]
# Task Description

# Open Questions

# Notes

# Task List

The following tasks will need to be carried out:
* [x] Set up `mkdocs`.
  * [x] Add dark mode and set it to the default.
  * [x] Add a `Dockerfile` and `docker-compose.yml` configuration.
* [x] Add initial pages.
  * [x] Add example usage for Maven.
  * [x] Add example usage for Gradle.
* [x] Set up Github pages.
* [x] Set up Netlify.
* [x] Add the required steps to the Github workflow.
* [ ] Add a github.io page.

# Useful Commands

# Incurred Costs

# Task Relationships

This task:
* Is a sub-task of: 
* Depends on: 
* Is a follow-up of: 
* Relates to: 

# Resources

# Useful Links

* [Github: Using Custom Workflows With Github Pages](https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages#configuring-the-upload-pages-artifact-action)

# Points of Contact

* @carlspring 
* @steve-todorov
