### ISSUE TITLE
Make it possible to specify via a property whether to use hypens or slashes for the test method's path

### ISSUE THREAD

**Issue by carlspring** [carlspring/idempotence#36]
# Task Description

As explained in [the documentation](https://carlspring.github.io/idempotence/developers-guide/conceptual-overview/#directory-structure):

* For a Gradle project, with a test called `GradleBasicFunctionalityTest` with a method `testMultipleWithPatterns`,
  they will be placed under:
```
build/test-resources/GradleBasicFunctionalityTest-testMultipleWithPatterns/nested/dir/foo.txt
build/test-resources/GradleBasicFunctionalityTest-testMultipleWithPatterns/testMultipleWithPatterns/foo.txt
```

* For a Maven project, with a test called `MavenBasicFunctionalityTest` with a method `testMultipleWithPatterns`,
  they will be placed under:
```
target/test-resources/MavenBasicFunctionalityTest-testMultipleWithPatterns/nested/dir/foo.txt
target/test-resources/MavenBasicFunctionalityTest-testMultipleWithPatterns/foo.txt
```

It should be possible to specify via a property whether to use hypens or slashes for the test method's path, so that you can pick between:
```
build/test-resources/GradleBasicFunctionalityTest-testMultipleWithPatterns/nested/dir/foo.txt
```
And:
```
build/test-resources/GradleBasicFunctionalityTest/testMultipleWithPatterns/nested/dir/foo.txt
```

This can be controlled by a property like `org.carlspring.testing.idempotence.target.separator`.

# Open Questions

# Notes

# Task List

The following tasks will need to be carried out:
* [ ] Investigate the issue.
* [ ] Provide a solution.
* [ ] Implement tests.
  * [ ] Implement unit tests.
  * [ ] Implement integration tests.
* [ ] Test the fix.
* [ ] Update the documentation.

# Useful Commands

# Incurred Costs

# Task Relationships

This task:
* Is a sub-task of: 
* Depends on: 
* Is a follow-up of: 
* Relates to: 

# Resources

# Useful Links

* [Idempotence: Docs](https://carlspring.github.io/idempotence/)

# Points of Contact
