### ISSUE TITLE
Implement support for SBT

### ISSUE THREAD

**Issue by carlspring** [carlspring/idempotence#40]
# Task Description

We need to check if the Maven dependency is sufficient for use under SBT. If not, we need to implement an extension for it.

# Open Questions

# Notes

# Task List

The following tasks will need to be carried out:
* [ ] Investigate whether the `idempotence-maven` dependency is enough for use from an SBT project.
* [ ] Provide a solution.
  * [ ] Create a new Maven module called `idempotence-sbt`.
  * [ ] Have a look at the code in the `idempotence-gradle` module and follow the same approach.
* [ ] Test the fix.
  * [ ] Write unit tests.
  * [ ] Add a new Maven module called `idempotence-sbt-integration-tests` and use the scripts from the `idempotence-gradle-integration-tests` module as inspiration of how to implement this for SBT.
    * [ ] Create a sample SBT project.
    * [ ] Implement tests in a similar way to the ones in the `idempotence-gradle-integration-tests`.
* [ ] Update the documentation.

# Useful Commands

# Incurred Costs

# Task Relationships

This task:
* Is a sub-task of: 
* Depends on: 
* Is a follow-up of: 
* Relates to: 

# Resources

# Useful Links

# Points of Contact

* @carlspring
