### ISSUE TITLE
Implement a Maven extension

### ISSUE THREAD

**Issue by carlspring** [carlspring/idempotence#9]
# Task Description

The extension should be a separate module and contain a class that has a `@PostConstruct` method which sets:
```
org.carlspring.testing.idempotence.basedir=target/test-resources
```

Currently, this is hard-coded in `IdempotenceProperties` to default to `target/test-resources`, if no value is set for the`org.carlspring.testing.idempotence.basedir` System property.

# Open Questions

# Notes

# Task List

The following tasks will need to be carried out:
* [x] Investigate the issue.
* [x] Provide a solution.
* [x] Test the fix.
* [x] Update the documentation.

# Useful Commands

# Incurred Costs

# Task Relationships

This task:
* Is a sub-task of: 
* Depends on: 
* Is a follow-up of: 
* Relates to: 
  * #10

# Resources

# Useful Links

# Points of Contact

* @carlspring

**Comment by carlspring** [comment]
Implemented.
